name: CICD
on:
  pull_request:
jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - macOS
        go:
          - 21
    name: '${{ matrix.platform }} | 1.${{ matrix.go }}.x'
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.${{ matrix.go }}.x
          cache: true
      - run: |
          export GOBIN=$HOME/go/bin
          case "${{ matrix.go }}" in
            14|15) _version='';;
            *) _version='@latest';;
          esac
      - run: PATH=$HOME/go/bin/:$PATH make test

